### ISSUE TITLE
Image loads out of screen

### ISSUE THREAD

**Issue by incherre** [DrexelChatbotGroup/DrexelChatbot#39]
## Steps to reproduce:
1. Go to the Drexel Chatbot website
2. Ask "Show me Main."
3. Wait for the image to render

## Effects:
Image is loaded sometimes below the bottom of the screen and the window does not automatically scroll up.
![image](https://cloud.githubusercontent.com/assets/23296980/26473209/316abd54-4178-11e7-84dc-c2d850a87379.png)

**Comment by tpa27** [comment]
Fixed for now, but this functionality should be moved into the front-end apps themselves, not handled in the backend. I'm going to make a new issue for that.
