### ISSUE TITLE
Database queries are case sensitive

### ISSUE THREAD

**Issue by tpa27** [DrexelChatbotGroup/DrexelChatbot#6]
"What is mongan's email" will not work, for example

**Comment by incherre** [comment]
Is this issue still open?

**Comment by tpa27** [comment]
This is still open, but I think I can fix it easily. I can force all names in the database to be lowercase by changing the ttl.py, and then force every query to be lowercase by changing the stardog.py. I will try this out soon.

**Comment by tpa27** [comment]
My original idea to fix this didn't work, so I put in a minor fix to make it better. When the query is read in gqc, I just make the first letter of nouns capital. Since the database has the information stored the same way, this works out.
